classdef SamplingAliasingDemo < handle
    %SAMPLINGALIASINGDEMO 采样定理与混叠的交互演示
    %   通过两个滑块分别调节信号频率 f0 与采样频率 fs，实时观察：
    %     上图——真实连续信号、采样点、由采样点恢复出的信号
    %     下图——真实频率与混叠(表观)频率，并标注奈奎斯特频率 fs/2
    %   用于直观理解"完全采样"的条件 fs>2*f_max，以及欠采样导致的混叠。
    %
    %   用法（一般由主程序"步骤8"的按钮启动）：
    %     SamplingAliasingDemo();

    properties
        % ---- GUI 组件 ----
        fig
        axTime
        axFreq
        txtInfo
        sliderF0
        sliderFs
        lblF0
        lblFs

        % ---- 参数 ----
        f0   (1,1) double = 2.0    % 信号频率 (Hz)
        fs   (1,1) double = 8.0    % 采样频率 (Hz)
        Twin (1,1) double = 1.0    % 显示时长 (s)
    end

    methods
        function obj = SamplingAliasingDemo()
            %构造函数：创建界面并绘制初始状态
            obj.buildGUI();
            obj.updatePlots();
        end
    end

    methods (Access = private)
        function buildGUI(obj)
            %BUILDGUI 创建交互演示窗口
            obj.fig = figure('Name', '采样定理与混叠 - 交互演示', ...
                'NumberTitle', 'off', ...
                'MenuBar', 'none', ...
                'ToolBar', 'none', ...
                'Position', [120, 80, 1120, 720], ...
                'Color', [0.95, 0.95, 0.95]);

            % ---- 时域坐标轴 ----
            obj.axTime = axes('Parent', obj.fig, ...
                'Units', 'normalized', ...
                'Position', [0.09, 0.47, 0.88, 0.50]);

            % ---- 频域坐标轴 ----
            obj.axFreq = axes('Parent', obj.fig, ...
                'Units', 'normalized', ...
                'Position', [0.09, 0.20, 0.54, 0.19]);

            % 为坐标轴启用工具栏（含"导出"按钮）
            try
                axtoolbar(obj.axTime, ...
                    {'export', 'datacursor', 'pan', 'zoomin', ...
                     'zoomout', 'restoreview'});
                axtoolbar(obj.axFreq, ...
                    {'export', 'datacursor', 'pan', 'zoomin', ...
                     'zoomout', 'restoreview'});
            catch
                % 若当前 MATLAB 版本不支持则忽略
            end

            % ---- 状态信息面板 ----
            pnlInfo = uipanel('Parent', obj.fig, ...
                'Units', 'normalized', ...
                'Position', [0.67, 0.18, 0.31, 0.22], ...
                'Title', '采样状态', ...
                'FontSize', 11, ...
                'BackgroundColor', [1, 1, 1]);
            obj.txtInfo = uicontrol('Parent', pnlInfo, ...
                'Style', 'text', ...
                'Units', 'normalized', ...
                'Position', [0.05, 0.05, 0.90, 0.90], ...
                'String', '', ...
                'FontSize', 11, ...
                'FontName', 'Microsoft YaHei', ...
                'BackgroundColor', [1, 1, 1], ...
                'HorizontalAlignment', 'left');

            % ---- 参数控制面板 ----
            pnlCtrl = uipanel('Parent', obj.fig, ...
                'Units', 'normalized', ...
                'Position', [0.02, 0.015, 0.96, 0.15], ...
                'Title', '参数调节', ...
                'FontSize', 11, ...
                'BackgroundColor', [0.9, 0.95, 1]);

            % 信号频率 f0
            uicontrol('Parent', pnlCtrl, 'Style', 'text', ...
                'String', '信号频率 f0 =', ...
                'Units', 'normalized', 'Position', [0.02, 0.56, 0.12, 0.34], ...
                'FontSize', 10, 'FontName', 'Microsoft YaHei', ...
                'BackgroundColor', [0.9, 0.95, 1], ...
                'HorizontalAlignment', 'left');
            obj.lblF0 = uicontrol('Parent', pnlCtrl, 'Style', 'text', ...
                'String', sprintf('%.2f Hz', obj.f0), ...
                'Units', 'normalized', 'Position', [0.14, 0.56, 0.09, 0.34], ...
                'FontSize', 10, 'FontName', 'Microsoft YaHei', ...
                'BackgroundColor', [0.9, 0.95, 1], ...
                'HorizontalAlignment', 'left');
            obj.sliderF0 = uicontrol('Parent', pnlCtrl, 'Style', 'slider', ...
                'Units', 'normalized', 'Position', [0.24, 0.59, 0.20, 0.28], ...
                'Min', 0.5, 'Max', 6, 'Value', obj.f0, ...
                'SliderStep', [0.02, 0.1], ...
                'BackgroundColor', [0.9, 0.95, 1], ...
                'Callback', @(src, ~) obj.onF0Changed(src));

            % 采样频率 fs
            uicontrol('Parent', pnlCtrl, 'Style', 'text', ...
                'String', '采样频率 fs =', ...
                'Units', 'normalized', 'Position', [0.02, 0.10, 0.12, 0.34], ...
                'FontSize', 10, 'FontName', 'Microsoft YaHei', ...
                'BackgroundColor', [0.9, 0.95, 1], ...
                'HorizontalAlignment', 'left');
            obj.lblFs = uicontrol('Parent', pnlCtrl, 'Style', 'text', ...
                'String', sprintf('%.2f Hz', obj.fs), ...
                'Units', 'normalized', 'Position', [0.14, 0.10, 0.09, 0.34], ...
                'FontSize', 10, 'FontName', 'Microsoft YaHei', ...
                'BackgroundColor', [0.9, 0.95, 1], ...
                'HorizontalAlignment', 'left');
            obj.sliderFs = uicontrol('Parent', pnlCtrl, 'Style', 'slider', ...
                'Units', 'normalized', 'Position', [0.24, 0.13, 0.20, 0.28], ...
                'Min', 1, 'Max', 20, 'Value', obj.fs, ...
                'SliderStep', [0.02, 0.1], ...
                'BackgroundColor', [0.9, 0.95, 1], ...
                'Callback', @(src, ~) obj.onFsChanged(src));

            % 重置按钮
            uicontrol('Parent', pnlCtrl, 'Style', 'pushbutton', ...
                'String', '重置', ...
                'Units', 'normalized', 'Position', [0.47, 0.35, 0.10, 0.34], ...
                'FontSize', 10, 'BackgroundColor', [1, 0.8, 0.8], ...
                'Callback', @(~, ~) obj.onReset());

            % 提示文字
            uicontrol('Parent', pnlCtrl, 'Style', 'text', ...
                'String', {'提示：拖动滑块改变 f0 与 fs。', ...
                           '当 fs ≤ 2·f0 时出现混叠。'}, ...
                'Units', 'normalized', 'Position', [0.60, 0.10, 0.38, 0.80], ...
                'FontSize', 10, 'FontName', 'Microsoft YaHei', ...
                'BackgroundColor', [0.9, 0.95, 1], ...
                'HorizontalAlignment', 'left');
        end

        function onF0Changed(obj, src)
            %ONF0CHANGED 信号频率滑块回调
            obj.f0 = get(src, 'Value');
            set(obj.lblF0, 'String', sprintf('%.2f Hz', obj.f0));
            obj.updatePlots();
        end

        function onFsChanged(obj, src)
            %ONFSCHANGED 采样频率滑块回调
            obj.fs = get(src, 'Value');
            set(obj.lblFs, 'String', sprintf('%.2f Hz', obj.fs));
            obj.updatePlots();
        end

        function onReset(obj)
            %ONRESET 恢复默认参数
            obj.f0 = 2.0;
            obj.fs = 8.0;
            set(obj.sliderF0, 'Value', obj.f0);
            set(obj.sliderFs, 'Value', obj.fs);
            set(obj.lblF0, 'String', sprintf('%.2f Hz', obj.f0));
            set(obj.lblFs, 'String', sprintf('%.2f Hz', obj.fs));
            obj.updatePlots();
        end

        function updatePlots(obj)
            %UPDATEPLOTS 根据当前 f0 / fs 刷新两个坐标轴与状态文本
            f0 = obj.f0;
            fs = obj.fs;
            Twin = obj.Twin;

            t = linspace(0, Twin, 4000);
            x = sin(2*pi*f0*t);

            ts = 0:1/fs:Twin;
            if ts(end) < Twin - 1e-9
                ts(end+1) = Twin;
            end
            xs = sin(2*pi*f0*ts);

            % 采样后的等效(别名)频率，取 (-fs/2, fs/2]
            fEff   = f0 - fs*round(f0/fs);
            falias = abs(fEff);
            xa     = sin(2*pi*fEff*t);
            aliased = fs <= 2*f0 + 1e-9;

            % ---------- 时域 ----------
            if isvalid(obj.axTime)
                legend(obj.axTime, 'off');
                cla(obj.axTime);
            end
            hold(obj.axTime, 'on');
            plot(obj.axTime, t, x, 'b-', 'LineWidth', 1.8);
            stem(obj.axTime, ts, xs, 'r', 'LineWidth', 1, ...
                'MarkerSize', 6, 'MarkerFaceColor', 'r');
            plot(obj.axTime, t, xa, 'm--', 'LineWidth', 1.6);
            hold(obj.axTime, 'off');
            grid(obj.axTime, 'on');
            xlabel(obj.axTime, '时间 (s)');
            ylabel(obj.axTime, '幅度');
            xlim(obj.axTime, [0, Twin]);
            ylim(obj.axTime, [-1.8, 1.8]);
            title(obj.axTime, sprintf( ...
                '时域：f_0=%.2f Hz，f_s=%.2f Hz（%d 个采样点）', ...
                f0, fs, numel(ts)));
            legend(obj.axTime, ...
                {'真实连续信号', '采样点', '由采样点恢复的信号'}, ...
                'Location', 'south', 'Orientation', 'horizontal');
            if aliased
                text(obj.axTime, Twin/2, 1.55, ...
                    '恢复信号 ≠ 真实信号 → 发生混叠', ...
                    'Color', [0.8 0 0], 'FontSize', 11, 'FontWeight', 'bold', ...
                    'HorizontalAlignment', 'center');
            else
                text(obj.axTime, Twin/2, 1.55, ...
                    '恢复信号与真实信号重合 → 无混叠', ...
                    'Color', [0 0.5 0], 'FontSize', 11, 'FontWeight', 'bold', ...
                    'HorizontalAlignment', 'center');
            end

            % ---------- 频域 ----------
            if isvalid(obj.axFreq)
                legend(obj.axFreq, 'off');
                cla(obj.axFreq);
            end
            fmax = max([fs, 2*f0, 1])*1.15;
            hold(obj.axFreq, 'on');
            patch(obj.axFreq, [0 fs/2 fs/2 0], [0 0 1.25 1.25], ...
                [0.6 1 0.6], 'FaceAlpha', 0.25, 'EdgeColor', 'none');
            stem(obj.axFreq, f0, 1, 'b', 'LineWidth', 1.6, ...
                'MarkerFaceColor', 'b');
            stem(obj.axFreq, falias, 0.7, 'r', 'LineWidth', 1.6, ...
                'MarkerFaceColor', 'r');
            plot(obj.axFreq, [fs/2 fs/2], [0 1.3], 'k--', 'LineWidth', 1.2);
            hold(obj.axFreq, 'off');
            grid(obj.axFreq, 'on');
            xlim(obj.axFreq, [0, fmax]);
            ylim(obj.axFreq, [0, 1.4]);
            xlabel(obj.axFreq, '频率 (Hz)');
            ylabel(obj.axFreq, '相对幅度');
            title(obj.axFreq, sprintf('频域：奈奎斯特频率 f_s/2=%.2f Hz', fs/2));
            legend(obj.axFreq, ...
                {'无混叠区 0~f_s/2', '真实频率 f_0', ...
                 '混叠频率 f_{alias}', '奈奎斯特频率 f_s/2'}, ...
                'Location', 'northeast', 'FontSize', 8);

            % ---------- 状态文本 ----------
            if aliased
                status = '欠采样 → 发生混叠';
                col = [0.8 0 0];
            else
                status = '满足采样定理 → 无混叠';
                col = [0 0.5 0];
            end
            info = sprintf(['信号频率 f0 = %.2f Hz\n' ...
                '采样频率 fs = %.2f Hz\n' ...
                '奈奎斯特频率 fs/2 = %.2f Hz\n' ...
                '最小采样率 2f0 = %.2f Hz\n' ...
                '表观(混叠)频率 = %.2f Hz\n' ...
                '状态：%s'], f0, fs, fs/2, 2*f0, falias, status);
            set(obj.txtInfo, 'String', info, 'ForegroundColor', col);
            drawnow limitrate;
        end
    end
end
