function fig = fid_anim_octave()
%FID_ANIM_OCTAVE FID 信号与傅里叶变换动画（Octave 版）
  baseDir = fileparts(mfilename('fullpath'));
  addpath(baseDir);
  oct_setup_fonts();

  fig = figure('Name', 'FID 信号与傅里叶变换动画（Octave版）', 'NumberTitle', 'off', ...
      'MenuBar', 'none', 'ToolBar', 'none', 'Position', [80 60 1150 720], ...
      'Color', [0.95 0.95 0.95]);
  st = struct();
  st.fig = fig;
  st.ax3 = axes('Parent', fig, 'Units', 'normalized', 'Position', [0.05 0.17 0.42 0.74]);
  st.axT = axes('Parent', fig, 'Units', 'normalized', 'Position', [0.55 0.17 0.42 0.74]);
  st.frame = 0; st.maxFrame = 160; st.running = false;
  setappdata(fig, 'anim_fid', st);

  pnl = uipanel('Parent', fig, 'Units', 'normalized', ...
      'Position', [0.02 0.02 0.96 0.11], 'Title', '动画控制', ...
      'BackgroundColor', [0.9 0.95 1]);
  uicontrol('Parent', pnl, 'Style', 'pushbutton', 'String', '开始动画', ...
      'Units', 'normalized', 'Position', [0.02 0.25 0.12 0.55], ...
      'Callback', @(~,~) oct_anim_run(fig, 'fid'));
  uicontrol('Parent', pnl, 'Style', 'pushbutton', 'String', '暂停/继续', ...
      'Units', 'normalized', 'Position', [0.16 0.25 0.12 0.55], ...
      'Callback', @(~,~) oct_anim_toggle(fig, 'fid'));
  uicontrol('Parent', pnl, 'Style', 'pushbutton', 'String', '重置', ...
      'Units', 'normalized', 'Position', [0.30 0.25 0.12 0.55], ...
      'Callback', @(~,~) oct_anim_reset(fig, 'fid'));
  uicontrol('Parent', pnl, 'Style', 'text', ...
      'String', '演示内容：宏观磁化矢量衰减螺旋与 FID 信号', ...
      'Units', 'normalized', 'Position', [0.46 0.25 0.52 0.55], ...
      'BackgroundColor', [0.9 0.95 1], 'HorizontalAlignment', 'left');
  oct_anim_draw(fig, 'fid');
end
