function fig = fourier_series_anim_octave()
%FOURIER_SERIES_ANIM_OCTAVE 傅里叶级数分解动画（Octave 版）
  baseDir = fileparts(mfilename('fullpath'));
  addpath(baseDir);
  oct_setup_fonts();

  fig = figure('Name', '傅里叶级数分解动画（Octave版）', 'NumberTitle', 'off', ...
      'MenuBar', 'none', 'ToolBar', 'none', 'Position', [80 60 1100 720], ...
      'Color', [0.95 0.95 0.95]);
  st = struct();
  st.fig = fig;
  st.axC = axes('Parent', fig, 'Units', 'normalized', 'Position', [0.06 0.17 0.40 0.74]);
  st.axT = axes('Parent', fig, 'Units', 'normalized', 'Position', [0.53 0.17 0.44 0.74]);
  st.frame = 0; st.maxFrame = 160; st.running = false;
  setappdata(fig, 'anim_series', st);

  pnl = uipanel('Parent', fig, 'Units', 'normalized', ...
      'Position', [0.02 0.02 0.96 0.11], 'Title', '动画控制', ...
      'BackgroundColor', [0.9 0.95 1]);
  uicontrol('Parent', pnl, 'Style', 'pushbutton', 'String', '开始动画', ...
      'Units', 'normalized', 'Position', [0.02 0.25 0.12 0.55], ...
      'Callback', @(~,~) oct_anim_run(fig, 'series'));
  uicontrol('Parent', pnl, 'Style', 'pushbutton', 'String', '暂停/继续', ...
      'Units', 'normalized', 'Position', [0.16 0.25 0.12 0.55], ...
      'Callback', @(~,~) oct_anim_toggle(fig, 'series'));
  uicontrol('Parent', pnl, 'Style', 'pushbutton', 'String', '重置', ...
      'Units', 'normalized', 'Position', [0.30 0.25 0.12 0.55], ...
      'Callback', @(~,~) oct_anim_reset(fig, 'series'));
  uicontrol('Parent', pnl, 'Style', 'text', ...
      'String', '演示内容：标准方波的傅里叶级数分解（旋转向量叠加）', ...
      'Units', 'normalized', 'Position', [0.46 0.25 0.52 0.55], ...
      'BackgroundColor', [0.9 0.95 1], 'HorizontalAlignment', 'left');
  oct_anim_draw(fig, 'series');
end
