function oct_show_text_window(winTitle, content)
%OCT_SHOW_TEXT_WINDOW 弹出可滚动、可复制的文本窗口
  f = figure('Name', winTitle, 'NumberTitle', 'off', 'MenuBar', 'none', ...
             'ToolBar', 'none', 'Position', [300, 200, 780, 540], 'Color', [1 1 1]);
  uicontrol('Parent', f, 'Style', 'edit', 'Units', 'normalized', ...
      'Position', [0.02 0.02 0.96 0.96], 'String', content, 'FontSize', 10, ...
      'HorizontalAlignment', 'left', 'Max', 100, 'Min', 0, 'Enable', 'on', ...
      'BackgroundColor', [1 1 1], 'ForegroundColor', [0.1 0.1 0.1]);
end
