function oct_step_11(ctx, txt)
%OCT_STEP_11 步骤11：完整总结（显示文本框）
  d = ctx.disp;
  uicontrol('Parent', ctx.fig, 'Style', 'edit', 'Units', 'normalized', ...
      'Position', [d(1)+0.03*d(3), d(2)+0.03*d(4), 0.94*d(3), 0.90*d(4)], ...
      'String', txt, 'FontSize', 10, 'HorizontalAlignment', 'left', ...
      'Max', 100, 'Min', 0, 'Enable', 'on', 'Tag', 'octstep', ...
      'BackgroundColor', [1 1 1], 'ForegroundColor', [0.1 0.1 0.1]);
  oct_sgtitle(ctx.fig, [d(1), d(2)+d(4)*0.945, d(3), d(4)*0.05], ...
              '步骤11：总结——傅里叶变换的意义', 14);
end
