function fig = sampling_aliasing_demo_octave()
%SAMPLING_ALIASING_DEMO_OCTAVE 采样定理与混叠交互演示（Octave 版）
%   拖动滑块改变信号频率 f0 与采样频率 fs，实时观察采样点、
%   恢复信号、混叠频率与奈奎斯特频率。
  baseDir = fileparts(mfilename('fullpath'));
  addpath(baseDir);
  oct_setup_fonts();

  fig = figure('Name', '采样定理与混叠 - 交互演示（Octave版）', ...
      'NumberTitle', 'off', 'MenuBar', 'none', 'ToolBar', 'none', ...
      'Position', [120, 80, 1120, 720], 'Color', [0.95 0.95 0.95]);

  S = struct();
  S.fig = fig;
  S.axT = axes('Parent', fig, 'Units', 'normalized', 'Position', [0.09 0.50 0.88 0.47]);
  S.axF = axes('Parent', fig, 'Units', 'normalized', 'Position', [0.09 0.19 0.54 0.19]);

  pnlInfo = uipanel('Parent', fig, 'Units', 'normalized', ...
      'Position', [0.67 0.18 0.31 0.22], 'Title', '采样状态', ...
      'FontSize', 11, 'BackgroundColor', [1 1 1]);
  S.txt = uicontrol('Parent', pnlInfo, 'Style', 'text', 'Units', 'normalized', ...
      'Position', [0.05 0.05 0.90 0.90], 'String', '', 'FontSize', 10, ...
      'BackgroundColor', [1 1 1], 'HorizontalAlignment', 'left');

  pnlC = uipanel('Parent', fig, 'Units', 'normalized', ...
      'Position', [0.02 0.015 0.96 0.15], 'Title', '参数调节', ...
      'FontSize', 11, 'BackgroundColor', [0.9 0.95 1]);

  uicontrol('Parent', pnlC, 'Style', 'text', 'String', '信号频率 f0 =', ...
      'Units', 'normalized', 'Position', [0.02 0.56 0.12 0.34], 'FontSize', 10, ...
      'BackgroundColor', [0.9 0.95 1], 'HorizontalAlignment', 'left');
  S.lblF0 = uicontrol('Parent', pnlC, 'Style', 'text', 'String', '2.00 Hz', ...
      'Units', 'normalized', 'Position', [0.14 0.56 0.09 0.34], 'FontSize', 10, ...
      'BackgroundColor', [0.9 0.95 1], 'HorizontalAlignment', 'left');
  S.slF0 = uicontrol('Parent', pnlC, 'Style', 'slider', 'Units', 'normalized', ...
      'Position', [0.24 0.59 0.20 0.28], 'Min', 0.5, 'Max', 6, 'Value', 2, ...
      'Callback', @(~,~) oct_demo_update(fig));

  uicontrol('Parent', pnlC, 'Style', 'text', 'String', '采样频率 fs =', ...
      'Units', 'normalized', 'Position', [0.02 0.10 0.12 0.34], 'FontSize', 10, ...
      'BackgroundColor', [0.9 0.95 1], 'HorizontalAlignment', 'left');
  S.lblFs = uicontrol('Parent', pnlC, 'Style', 'text', 'String', '8.00 Hz', ...
      'Units', 'normalized', 'Position', [0.14 0.10 0.09 0.34], 'FontSize', 10, ...
      'BackgroundColor', [0.9 0.95 1], 'HorizontalAlignment', 'left');
  S.slFs = uicontrol('Parent', pnlC, 'Style', 'slider', 'Units', 'normalized', ...
      'Position', [0.24 0.13 0.20 0.28], 'Min', 1, 'Max', 20, 'Value', 8, ...
      'Callback', @(~,~) oct_demo_update(fig));

  uicontrol('Parent', pnlC, 'Style', 'pushbutton', 'String', '重置', ...
      'Units', 'normalized', 'Position', [0.47 0.35 0.10 0.34], 'FontSize', 10, ...
      'BackgroundColor', [1 0.8 0.8], 'Callback', @(~,~) oct_demo_reset(fig));
  uicontrol('Parent', pnlC, 'Style', 'text', ...
      'String', {'提示：拖动滑块改变 f0 与 fs。', '当 fs ≤ 2·f0 时出现混叠。'}, ...
      'Units', 'normalized', 'Position', [0.60 0.10 0.38 0.80], 'FontSize', 10, ...
      'BackgroundColor', [0.9 0.95 1], 'HorizontalAlignment', 'left');

  setappdata(fig, 'demostate', S);
  oct_demo_update(fig);
end
